---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[inspec_package]
